import type { StepDefinition } from "@/types/database";

export interface AutomationPlan {
  name: string;
  description: string;
  triggerType: "webhook" | "schedule" | "form";
  triggerConfig: Record<string, any>;
  steps: StepDefinition[];
  safety: { risk: "low" | "medium" | "high" | "critical"; approvalRequired: boolean; reasons: string[] };
  assumptions: string[];
}

const has = (text: string, ...terms: string[]) => terms.some((t) => text.includes(t));
const step = (key: string, type: StepDefinition["type"], config: Record<string, any>): StepDefinition => ({ key, type, config });

type RiskLevel = AutomationPlan["safety"]["risk"];
const RISK_RANK: Record<RiskLevel, number> = { low: 0, medium: 1, high: 2, critical: 3 };
// Escalates risk only — never silently downgrades a higher risk that was already
// assigned earlier in the scan, regardless of the order these checks run in.
const escalate = (current: RiskLevel, next: RiskLevel): RiskLevel =>
  RISK_RANK[next] > RISK_RANK[current] ? next : current;

export function architectAutomation(request: string): AutomationPlan {
  const raw = request.trim();
  const text = raw.toLowerCase();
  if (!raw) throw new Error("Describe what you want BusiGo to automate.");

  const steps: StepDefinition[] = [];
  const assumptions: string[] = [];
  const reasons: string[] = [];
  let risk: AutomationPlan["safety"]["risk"] = "low";
  let triggerType: AutomationPlan["triggerType"] = "webhook";
  let triggerConfig: Record<string, any> = {};

  if (has(text, "every day", "daily", "each morning", "every morning", "every monday", "weekly")) {
    triggerType = "schedule";
    triggerConfig = { cron: has(text, "morning") ? "0 9 * * *" : "0 9 * * 1" };
  } else if (has(text, "form", "form submission", "website form")) {
    triggerType = "form";
  }

  if (has(text, "qualif", "classif", "score", "analyz", "analyze")) {
    steps.push(step("step1", "ai_action", {
      mode: "classify",
      categories: ["high_priority", "medium_priority", "low_priority"],
      input: "{{trigger}}",
      instruction: "Analyze the incoming business event and classify its priority. Return only a JSON object with category and reason.",
    }));
  }

  if (has(text, "wait", "after", "follow up", "follow-up")) {
    steps.push(step(`step${steps.length + 1}`, "delay", { amount: 1, unit: "days" }));
  }

  if (has(text, "email", "reply", "respond", "notify", "message")) {
    const requiresExternal = has(text, "customer", "client", "lead", "prospect");
    steps.push(step(`step${steps.length + 1}`, "send_email", {
      to: "{{trigger.email}}",
      subject: "Following up with you",
      body: "Hello,\n\nThanks for reaching out. We received your message and will follow up shortly.\n\nBusiGo",
    }));
    if (requiresExternal) { risk = escalate(risk, "medium"); reasons.push("This automation can communicate externally with customers or leads."); }
  }

  if (has(text, "http", "api", "webhook", "call an api")) {
    steps.push(step(`step${steps.length + 1}`, "http_request", { method: "POST", url: "", body: "{}" }));
    risk = escalate(risk, "medium");
    reasons.push("An external API call requires a configured endpoint and permission boundary.");
  }

  if (has(text, "summar", "extract", "generate", "write")) {
    steps.push(step(`step${steps.length + 1}`, "ai_action", {
      mode: "generate",
      instruction: raw,
      input: "{{trigger}}",
    }));
  }

  if (has(text, "invoice", "payment", "refund", "charge", "transfer", "money", "financial")) {
    risk = escalate(risk, "high");
    reasons.push("Financial activity must remain behind explicit human approval.");
  }
  if (has(text, "delete", "remove", "terminate", "cancel account")) {
    risk = escalate(risk, "critical");
    reasons.push("Destructive actions require explicit human approval and should be reviewed before activation.");
  }

  if (!steps.length) {
    steps.push(step("step1", "ai_action", {
      mode: "summarize",
      instruction: `Understand this business request and produce a concise execution-ready summary: ${raw}`,
      input: "{{trigger}}",
    }));
    assumptions.push("The request was ambiguous, so BusiGo created a safe AI analysis step instead of guessing a side effect.");
  }

  return {
    name: raw.length > 60 ? `${raw.slice(0, 57)}...` : raw,
    description: "Generated by BusiGo Automation Architect from a natural-language business goal.",
    triggerType,
    triggerConfig,
    steps,
    safety: { risk, approvalRequired: risk !== "low", reasons },
    assumptions,
  };
}

export function validateAutomationPlan(plan: AutomationPlan) {
  const errors: string[] = [];
  if (!plan.steps.length) errors.push("Automation must contain at least one step.");
  const keys = new Set<string>();
  for (const s of plan.steps) {
    if (!s.key || keys.has(s.key)) errors.push(`Duplicate or missing step key: ${s.key || "unknown"}`);
    keys.add(s.key);
    if (s.type === "http_request" && !s.config.url) errors.push(`${s.key}: configure the HTTP endpoint before publishing.`);
    if (s.type === "send_email" && !s.config.to) errors.push(`${s.key}: configure a recipient before publishing.`);
    if (s.type === "delay" && Number(s.config.amount) <= 0) errors.push(`${s.key}: delay amount must be greater than zero.`);
  }
  if (plan.triggerType === "schedule" && !plan.triggerConfig?.cron) errors.push("Scheduled automations require a cron expression.");
  return { valid: errors.length === 0, errors };
}
