import { createServerSupabase } from "@/lib/supabase/server";
import { getBusinessContext } from "@/lib/business-os";
import { getWorkspaceContext } from "@/lib/workspace/context";
import { BusinessPhaseBar } from "@/components/dashboard/BusinessPhaseBar";
import { Card } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";

export default async function InsightsPage() {
  const supabase = createServerSupabase(); const { data: { user } } = await supabase.auth.getUser(); if (!user) return null;
  const { workspace } = await getWorkspaceContext();
  const { business, opportunities, kpis, approvals } = await getBusinessContext(workspace.id);
  const score = Math.min(100, Math.round((business ? 30 : 0) + Math.min(30, opportunities.length * 3) + Math.min(20, kpis.length * 2) + (approvals.length ? 10 : 20)));
  return <div className="mx-auto max-w-6xl space-y-6"><div><h1 className="text-2xl font-bold text-ink">Business Insights</h1><p className="mt-1 text-sm text-slate">Phase 5 — turn business data into decisions, opportunities and measurable outcomes.</p></div><BusinessPhaseBar current={5}/><div className="grid gap-4 sm:grid-cols-4"><Card><p className="text-xs uppercase text-slate">Business OS score</p><p className="mt-2 text-3xl font-bold text-ink">{score}/100</p></Card><Card><p className="text-xs uppercase text-slate">Opportunities</p><p className="mt-2 text-3xl font-bold text-ink">{opportunities.length}</p></Card><Card><p className="text-xs uppercase text-slate">KPIs tracked</p><p className="mt-2 text-3xl font-bold text-ink">{kpis.length}</p></Card><Card><p className="text-xs uppercase text-slate">Approvals</p><p className="mt-2 text-3xl font-bold text-ink">{approvals.length}</p></Card></div><Card><div className="flex items-center justify-between"><h2 className="font-bold text-ink">AI business briefing</h2><Badge tone="signal">Live data</Badge></div><div className="mt-4 space-y-3 text-sm text-slate"><p><strong className="text-ink">Business foundation:</strong> {business ? "Your business profile is available to the Business Brain." : "Complete Business Brain to unlock deeper recommendations."}</p><p><strong className="text-ink">Priority:</strong> {opportunities[0]?.title || "Run the opportunity scanner and add your first automation opportunity."}</p><p><strong className="text-ink">Safety:</strong> {approvals.length ? `${approvals.length} high-impact actions are waiting for human review.` : "No pending high-impact actions."}</p></div></Card><Card><h2 className="font-bold text-ink">KPI history</h2>{kpis.length ? <div className="mt-3 divide-y divide-hairline">{kpis.map((k: any) => <div key={k.id} className="flex items-center justify-between py-3 text-sm"><span className="text-slate">{k.name}</span><strong className="text-ink">{k.value} {k.unit || ""}</strong></div>)}</div> : <p className="mt-3 text-sm text-slate">Connect business data or add KPI definitions to start measuring outcomes.</p>}</Card></div>;
}
